export const STRINGS = {
  EMAIL_INPUT_NAME: 'email',
  EMAIL_REQUIRED: 'Email is required.',
  PASSWORD_INPUT_NAME: 'password',
  NAME_INPUT: 'name',
  COUNTRY_INPUT: 'country',
  CITY_INPUT: 'city',
  CIRCUIT_INPUT: 'circuit',
  END_DATE_NAME: 'end-date',
  START_TIME_NAME: 'start-time',
  START_DATE_NAME: 'start-date',
  CHAMPIONSHIP_INPUT: 'championship-name',
  EVENT_INPUT: 'event-name',
  CHAMPIONSHIP_DETAILS: 'details',
  USER_ROLE: 'role',
  PASSWORD_REQUIRED: 'Password is required.',
  EMAIL: 'Email',
  PASSWORD: 'Password',
  LOGIN: 'Login',
  PASSWORD_LABEL: 'Password',
  EMAIL_LABEL: 'Email',
  NAME_LABEL: 'Name',
  COUNTRY: 'Country',
  CITY: 'City',
  NAME_REQUIRED: 'Name is required.',
  USER_ROLE_LABEL: 'Role',
  COUNTRY_REQUIRED: 'Country is required.',
  CITY_REQUIRED: 'City is required.',
  VALUE_CANNOT_BE_ONLY_SPACES: 'Value cannot be only spaces.',
  NAME_PLACEHOLDER: 'Enter user name',
  PASSWORD_PLACEHOLDER: 'Enter your password',
  COUNTRY_NAME_PLACEHOLDER: 'E.g. United Kingdom',
  CITY_NAME_PLACEHOLDER: 'E.g. Lianelli',
  CIRCUIT_NAME_PLACEHOLDER: 'E.g. Pembrey Circuit',
  EVENT_NAME_PLACEHOLDER: 'Enter event name',
  KEEP_ME_SIGNED_IN_CHECKBOX_NAME: 'Remember me',
  KEEP_ME_SIGNED_IN: 'Keep me signed in',
  FORGOT_PASSWORD: 'Forgot Password?',
  BUTTON_LABEL_LOGIN: 'Log In',
  ADD_USER: 'Add User',
  REMEMBER_ME: 'Remember me',
  EMAIL_INVALID: 'Email is invalid.',
  END_DATE_MUST_BE_GREATER: 'End date must be greater than start date.',
  SEND_EMAIL: 'Send',
  LOG_IN: 'Log In?',
  FORGOT_LOGIN: 'Log in',
  LOGOUT: 'Logout',
  DASHBOARD: 'Dashboard',
  HOME: 'Home',
  LOGOUT_CONTENT: 'Are you sure you want to logout?',
  CONFIRM: 'Confirm',
  CANCEL: 'Cancel',
  NAME: 'Name',
  REQUEST_DATE: 'Request Date',
  OUT_OF: 'Out of',
  NO_RECORDS_FOUND: 'No matched records found',
  NO_OF_ROWS: 'No. of Rows',
  ACCEPT_USER_CONTENT: 'Are you sure you want to approve this user?',
  ACCEPT_USER: 'Approve User',
  REJECT_USER_CONTENT: 'Are you sure you want to reject this user?',
  REJECT_USER: 'Reject User',
  USERS: 'Users',
  REQUESTS: 'Requests',
  REGISTERED: 'Registered',
  REQUESTED: 'Requested',
  INVITED: 'Invited',
  IMPORT_CSV: 'Import CSV',
  FILE_TYPE_REJECTED: 'Selected file format is not supported! Please choose .csv file format',
  PREPARING: 'preparing',
  DONE: 'done',
  OKAY: 'Okay',
  START_DATE: 'Start Date',
  END_DATE: 'End Date',
  DATE: 'Date',
  START_TIME: 'Time',
  EVENT_NAME: 'Event Name',
  PERCENTAGE: 'Percentage',
  FILE: 'file',
  ACCESS: 'Access',
  LOG_OUT: 'Log Out',
  SUCCESS: 'success',
  ERROR: 'error',
  SEARCH: 'Search',
  LOCATION: 'Location',
  SAVE: 'Save',
  NA: 'NA',
  ADDRESS: 'Address',
  DOB: 'D.O.B.',
  PHONE_NO: 'Phone No.',
  FILE_NOT_UPLOADED_YET: 'File not uploaded yet.',
  UPLOAD: 'Upload',
  OR: 'Or',
  FOR: 'for',
  PROFILE: 'profile',
  ADD: 'Add',
  EDIT: 'Edit',
  ADD_ADMIN: 'Add Admin',
  REMOVE_ADMIN: "Remove Admin",
  ADMINS: 'Admins',
  PLUS: '+',
  MINUS: '-',
  CHECKIN_PLACEHOLDER: 'Select',
  INVALID_NAME: 'Name cannot have digits or special characters.',
  NUMBER_REQUIRED: "Number required",
  USER_TYPE_INPUT: 'user_type',
}
