export const STRINGS = {
  EMAIL_INPUT_NAME: 'email',
  EMAIL_REQUIRED: 'Email is required.',
  EMAIL_PLACEHOLDER: 'Email',
  PASSWORD_INPUT_NAME: 'password',
  USER_ROLE: 'role',
  PASSWORD_REQUIRED: 'Password is required.',
  SHOW_NAME: 'show',
  LEAGUE_NAME: 'league',
  HOST_NAME: 'host',
  PLATFORM_NAME: 'platform',
  CONTENT_LENGTH: 'contentLength',
  START_TIME: 'startTime',
  PICK_DATE: 'date',
  END_TIME: 'endTime',
  SPORTS_NAME: 'sports',
  EMAIL: 'Email',
  PASSWORD: 'Password',
  LOGIN: 'Login',
  PASSWORD_LABEL: 'Password',
  EMAIL_LABEL: 'Email',
  VALUE_CANNOT_BE_ONLY_SPACES: 'Value cannot be only spaces.',
  PASSWORD_PLACEHOLDER: 'Password',
  FORGOT_PASSWORD: 'Forgot Password?',
  BUTTON_LABEL_LOGIN: 'Sign In',
  EMAIL_INVALID: 'Email is invalid.',
  LOG_IN: 'Log In?',
  FORGOT_LOGIN: 'Log in',
  LOGOUT: 'Logout',
  HOME: 'Home',
  LOGOUT_CONTENT: 'Are you sure you want to logout?',
  CONFIRM: 'Confirm',
  CANCEL: 'Cancel',
  NAME: 'Name',
  NO_RECORDS_FOUND: 'No matched records found',
  LOG_OUT: 'Log Out',
  SUCCESS: 'success',
  ERROR: 'error',
  SHOW_LIMIT: 5
}
